name: example

on: [push]

jobs:
  example:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install Conan
      run: | 
        python -m pip install conan==1.32.0
        conan profile new default --detect
    - name: Export recipe
      run: conan export . lumicks/stable
    - name: Test example project
      run: |
         cd example
         mkdir build
         cd build
         conan install .. --build=missing
         cmake ..
         cmake --build .
         ./bin/example.exe
