name: test_package

on: push

jobs:
  test_package:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        embedded-py: [3.8.10, 3.10.4]
        target_arch: [x86_64]
        include:
          - target_arch: armv8
            os: macos-latest
            embedded-py: 3.10.4
    env:
      create_pck: conan create . lumicks/testing -o embedded_python:version=${{ matrix.embedded-py }} --build=missing
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install Conan
      run: | 
        python -m pip install conan==1.48.1
        conan config set general.revisions_enabled=True
        conan profile new default --detect
        conan profile update settings.compiler.cppstd=17 default
    - name: Update arch to arm for MacOS
      if: ${{ matrix.target_arch }}
      run: conan profile update settings.arch=${{ matrix.target_arch }} default
    - name: Conan cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.conan/data
          C:\.conan
        key: conan-cache-${{ runner.os }}-py${{ matrix.embedded-py }}-${{ hashFiles('conanfile.py', '**/test_package.yml') }}
    - name: Test baseline
      run: ${{ env.create_pck }}
    - name: Test with numpy env
      run: ${{ env.create_pck }} -o test_embedded_python:env=numpy
    - name: Test with nbconvert env
      run: ${{ env.create_pck }} -o test_embedded_python:env=nbconvert
