name: test_package

on: [push]

jobs:
  test_package:
    runs-on: windows-latest
    strategy:
      matrix:
        embedded-py: [3.7.7, 3.8.3]
    env:
      create_pck: conan create . lumicks/testing -o embedded_python:version=${{ matrix.embedded-py }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install Conan
      run: | 
        python -m pip install conan==1.25.2
        conan profile new default --detect
    - name: Test baseline
      run: ${{ env.create_pck }}
    - name: Test with pytest env
      run: ${{ env.create_pck }} -o test_embedded_python:env=pytest
    - name: Test with numpy env
      run: ${{ env.create_pck }} -o test_embedded_python:env=numpy
