name: test_package
on: push
jobs:
  test_package:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        embedded-py: [3.9.8, 3.11.5]
    env:
      create_pck: conan create . lumicks/testing -o embedded_python:version=${{ matrix.embedded-py }} --build=missing
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    - name: Set up CXX/C env
      if: ${{ matrix.os  == 'macos-latest' }}
      run: |
        echo CC=/usr/bin/clang >> $GITHUB_ENV
        echo CXX=/usr/bin/clang++ >> $GITHUB_ENV
    - name: Install Conan
      run: | 
        python -m pip install conan==1.59.0
        conan config set general.revisions_enabled=True
        conan profile new default --detect
        conan profile update settings.compiler.cppstd=17 default
    - name: Test core
      run: conan create ./core lumicks/testing -o embedded_python-core:version=${{ matrix.embedded-py }} --build=missing
    - name: Test baseline
      run: ${{ env.create_pck }}
    - name: Test with numpy env
      run: ${{ env.create_pck }} -o test_embedded_python:env=numpy
    - name: Test with nbconvert env
      run: ${{ env.create_pck }} -o test_embedded_python:env=nbconvert
    - name: Test with pylake env
      run: ${{ env.create_pck }} -o test_embedded_python:env=pylake
