name: test_package
on: push
jobs:
  test_package:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        embedded-py: [3.11.5, 3.12.10, 3.13.5]
    name: "${{ matrix.os }}, ${{ matrix.embedded-py }}"
    env:
      create_pck: conan create . -o embedded_python-core/*:version=${{ matrix.embedded-py }} --build=missing --user=lumicks --channel=testing
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - if: runner.os == 'macOS'
      name: Set up CC/CXX env
      run: |
        echo CC=/usr/bin/clang >> $GITHUB_ENV
        echo CXX=/usr/bin/clang++ >> $GITHUB_ENV
    - name: Install Conan
      run: |
        python -m pip install conan==2.18.1
        conan profile detect
    - name: Test core
      run: cd core && ${{ env.create_pck }}
    - name: Test baseline
      run: ${{ env.create_pck }}
    - name: Test with numpy env
      run: ${{ env.create_pck }} -o test_embedded_python/*:env=numpy
    - name: Test with nbconvert env
      run: ${{ env.create_pck }} -o test_embedded_python/*:env=nbconvert
    - name: Test with pylake env
      run: ${{ env.create_pck }} -o test_embedded_python/*:env=pylake
